/**
 * All of the control types.
 * @returns {object}
 */
const controlTypes = {
	BACK_DROP: 'backDrop',
	BAR: 'bar',
	BUTTON: 'button',
	CAROUSEL: 'carousel',
	CALENDAR: 'calendar',
	CHECKBOX: 'checkbox',
	CONTAINER: 'container',
	CONVERSION: 'conversion',
	DATE: 'date',
	DESCRIPTION: 'description',
	DIV: 'div',
	DONUT: 'donut',
	DRAWER: 'drawer',
	DRAWER_MENU: 'drawerMenu',
	EDITABLE_GRID: 'editableGrid',
	FILE_INPUT: 'fileInput',
	FILE_THUMBNAIL: 'fileThumbnail',
	FILE_PICKER: 'filePicker',
	GRID: 'grid',
	GRID_COLUMN_BLOCK: 'gridColumnBlock',
	GRID_FOOTER: 'gridFooter',
	GRID_HEADER: 'gridHeader',
	GRID_HEADER_CELL: 'gridHeaderCell',
	GROUP: 'group',
	GROUPED_BUTTONS: 'groupedButtons',
	GRID_CELL: 'gridCell',
	GRID_ROW: 'gridRow',
	HEADER: 'header',
	HEADING: 'heading',
	HYPERLINK: 'hyperlink',
	ICON: 'icon',
	IMAGE: 'image',
	INPUT: 'input',
	IS_WORKING: 'isWorking',
	LABEL: 'label',
	LEGEND: 'legend',
	LIGHT_BOX: 'lightbox',
	MENU: 'menu',
	PICKER: 'picker',
	POPUP: 'popup',
	PROGRESS: 'progress',
	RADIO: 'radio',
	RESIZER: 'resizer',
	SCATTER: 'scatter',
	SCORE: 'score',
	SEARCH_BAR: 'searchBar',
	SECTION: 'section',
	SLIDER: 'slider',
	SOURCE: 'source',
	SPAN: 'span',
	SPLIT_VIEW: 'splitView',
	TABS: 'tabs',
	TAGS: 'tags',
	TEXT: 'text',
	TEXT_AREA: 'textarea',
	TILE_LAYOUT: 'tileLayout',
	TOOLBAR: 'toolbar',
	TREE: 'tree',
	VIDEO: 'video',
	VIRTUAL_LIST: 'virtualList'
};

export default controlTypes;
